- application/index/view/home/home.html
- application/index/view/share/share.html
中文环境下 Chrome 会自动弹出翻译。参考其他文件，此更改可解决此情况。
> Change lang="en" to lang="zh_cn"

- static/js/admin/shares.js
> 修复 Admi n删除分享文件的JS错误

- application/index/model/FileManage.php
1，针对各浏览器的附件文件名的不同头信息格式。
2，解决Content-Type为text/html的问题。
已测试通过的浏览器：IE，Microsoft Edge，Chrome，Firefox，Safari（IOS、OSX端）
> 修复X-Sendfile模式时附件文件名和Content-Type异常的问题。

- application/index/model/CronHandler.php
> Revert "order 字段名添加分隔符"

- application/index/model/FileManage.php
- extend/PHPMailer/PHPMailer/PHPMailer.php
修复PHP7.3下filter_var废弃FILTER_FLAG_HOST_REQUIRED造成的错误
修复查询字段错误造成的文件夹创建500错误
> 修复邮件发送错误与文件夹创建错误

- pkg/serializer/setting.go
> Bad syntax for struct tag value `authn`

- models/init.go
fix the panic when sqlite3 is used in the conf
ref #550
Signed-off-by: mritd <mritd@linux.com>
> fix(db_driver): fix the panic when sqlite3 is used in the conf

- bootstrap/static.go
嵌入的静态资源需要调用来初始化
https://github.com/rakyll/statik/issues/32
> fix: statik data needs to be initialized

- pkg/serializer/setting.go
- routers/controllers/site.go
> feat: 追加config返回参数: registerEnabled

- pkg/filesystem/driver/s3/handler.go
Reverts cloudreve/Cloudreve#831
> Revert "delete $name policy condition" (Fix: #959)

- Dockerfile
Fix js heap out of memory
Fix can't find cloudreve for cloudreve has been renamed to Cloudreve
> Fix problems in Dockerfile

- pkg/webdav/file.go
修复[1053](https://github.com/cloudreve/Cloudreve/issues/1053)
> 修复webdav不能同时移动位置和重命名

- Dockerfile
> fix: docker build issue

- models/file.go
- models/file_test.go
- models/folder.go
- models/folder_test.go
- pkg/filesystem/manage_test.go
- updated for both file and folder
- add unit test for folder rename action
> Keep updated at column when rename

- pkg/task/tranfer.go
- pkg/task/transfer_test.go
文件中转 已完成文件计数 应在文件成功上传后+1 #1367
> fix: incorrect progress count

- bootstrap/init.go
- go.mod
- go.sum
- main.go
- pkg/conf/conf.go
> graceful 关闭服务器

- .github/workflows/build.yml
- .github/workflows/test.yml
- .travis.yml
- Dockerfile
- README.md
- bootstrap/embed.go
- bootstrap/fs.go
- go.mod
- main.go
修复[favico 加载 bug](https://forum.cloudreve.org/d/2526) 和 windows上面字体文件不能[加载](https://github.com/cloudreve/Cloudreve/pull/1278#issuecomment-1118364562)
> 初始化时解压zip文件读取内存中

- service/admin/user.go
> bug fix: 修复能够修改`默认用户`状态

- pkg/filemanager/manager/manager.go
- pkg/filemanager/manager/operation.go
- service/share/manage.go
#2432. frontend pr: https://github.com/cloudreve/frontend/pull/259
password rules, and frontend styles may need further discussion.
https://github.com/user-attachments/assets/e8a5a4d2-6822-462f-a3ae-27668564c9cd
> feat: fileshare custom password support

- application/migrator/model/init.go
Complete the requirement #2559
> Database.Type new mariadb option suggestion

- inventory/types/types.go
> feat: platform self-adaptation for file viewer application

- docker-compose.yml
> chore(docker compose): pin postgres to major version

- application/migrator/policy.go
> fix(upgrade v3): validation on unique magic var in either blob name or path
