application/index/controller/Explore.php, application/index/controller/Profile.php, application/index/controller/Share.php, application/index/model/AdminHandler.php
显示分享文件列表时根据分享时间倒序排列，最新分享的文件显示在最前，因为分享顺序并不一定按照文件上传顺序决定。
=> 分享文件列表根据分享时间排序而不应该是ID。

application/index/model/Directory.php
php basename()无法获取带中文字符的文件名(乱码)
=> PHP basename 中文乱码问题

application/index/model/FileManage.php
文件重命名时，文件后缀名之前的‘.’会导致验证失败，后台做校验时应该先去除后缀名部分。
=> 修复重命名文件时验证失败的问题

pkg/webdav/webdav.go
rclone在传输时会反复创建父目录, 导致cloudreve返回409, 最终导致传输失败.
因此检测如果是rclone则忽略文目录已存在错误
=> Feat: webdav 适配 rclone

models/migration.go, pkg/serializer/setting.go, routers/controllers/site.go
网盘部署在国内需要备案，备案后需在网站显示备案号
设置计划放在基本信息下面
但是想不好备案号放哪里。因为很多地方都是用css `position: fixed` 装饰，比如那个➕。所以很难插在底部因为会遮挡其他组件。
=> Feat: ICP 备案信息

main.go, middleware/session.go, pkg/cache/driver.go, pkg/conf/conf.go, pkg/conf/defaults.go
> 暂未添加Mysql，使用`localhost`地址Mysql会自动转换成`unix`进行连接
> 配置方法（一）
```
http
{
upstream cloudreve {
server unix:/run/cloudreve/cloudreve.sock;
}
server {
location / {
proxy_pass http://cloudreve;
}
}
}
```
> 配置方法（二）
```
http
{
server {
location / {
proxy_pass http://unix:/run/cloudreve/cloudreve.sock;
}
}
}
```
```
; Unix 相关
[Unix]
Listen = /run/cloudreve/cloudreve.sock
; Redis 相关
[Redis]
; Reids 连接方式，支持 tcp | udp | unix
; 默认 tcp
Network = unix
Server = /run/redis/redis.sock
Password =
DB = 0
```
=> 增加 Unix Socket（Unix 套接字）

Dockerfile
update node image to lts-buster, because the alpine image cannot be obtained on arm/arm64,
it will support `docker buildx` build after the upgrade.
Signed-off-by: mritd <mritd@linux.com>
=> chore(dockerfile): update node image to lts-buster

service/user/setting.go
Use the lowercased email address to create a request to Gravatar.
According to [Gravatar](https://en.gravatar.com/site/implement/hash/), the email address should be lowercase to create a consistent hash.  
There is a chance that a user registered with an email address containing uppercase characters. This can lead to a bug, that users will never get their avatar from Gravatar.
=> Fix: email address should be lowercase for requesting Gravatar

middleware/auth.go, models/user.go, routers/controllers/user.go, service/user/login.go, service/user/register.go
1. 未验证显示密码错误
1. ```GetUserByEmail```看语意是根据email取得user
2. 但是 sql 语句却只select已激活user
3. 导致login.go 拿不到正确的user资讯
4. 永远只会提示密码错误
2. 注册帐号时，如果尚未验证，再发一次验证信
1. 因为我这边也是用```GetUserByEmail```拿取user资讯，但是一直拿不到资讯，顺便发现了上面的bug
2. 现在改成如果已存在的使用者未激活，会这样提示
3. ![image](https://user-images.githubusercontent.com/73118488/108261924-3651c780-719f-11eb-83b7-2407e8e22532.png)
3. 并且再发送一次验证码
=> 注册帐号时，如果尚未验证，再发一次验证信

.gitignore, pkg/filesystem/file.go
(cherry picked from commit b9cd82b849065f0d1ad093708f09c8722339bf2a)
Fix https://github.com/cloudreve/Cloudreve/issues/677
=> Fix: 阿里云的 golang SDK 会把整个 object KEY也编码

pkg/filesystem/driver/s3/handler.go
"name" is not in the list of supported conditions for policies: [supported conditions](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html#sigv4-PolicyConditions)
With the current configuration, AWS S3 returns the same error as Scaleway Object Storage.
Details: #824
=> delete $name policy condition

pkg/webdav/prop.go
修复了displayname为空，potplayer可以正常使用webdav功能
=> fix webdav prop get

go.mod, go.sum, pkg/conf/conf.go, pkg/conf/defaults.go, pkg/filesystem/image.go, pkg/filesystem/image_test.go, pkg/thumb/image.go, pkg/thumb/image_test.go, routers/controllers/file.go
"github.com/nfnt/resize"换成	"golang.org/x/image/draw"，因为前者已经不维护了。
修复当批量重新生成本地缩略图时，oom崩溃——添加了并发限制，默认为cpu核心数，可配置
添加了local缩略图生成后强制GC，添加配置项，默认false
local缩略图可配置编码方式，默认jpg并设置85。
MaxTaskCount:  -1,
EncodeMethod:  "jpg",
GCAfterGen:    false,
EncodeQuality: 85,
=> local缩略图功能提升

routers/controllers/file.go
There are no C binding in this file. And for users to compile themselves, this line will cause compilation to fail for those who don't need sqlite support.
移除不必要的c binding，使用CGO=0时，这行会导致编译失败。禁用CGO会导致sqlite无法使用，但可以方便编译（不需要安装gcc，跨平台编译方便），这点可以在文档中说明。
=> Remove unnecessary import "C"

Dockerfile, docker-bootstrap.sh
This PR generally did 2 things:
1. Fix unintended behavior for docker image
In Dockerfile it claims that user can specify their own config file in /etc/cloudreve but in face cloudreve would never read config from this file as cloudreve always reads config file from the same folder where cloudreve binary lives except explicit config path are specified. Thus this pr fixes this problem.
Dockerfile 里说可以把配置文件丢  /etc/cloudreve 这样用户也可以把这个目录映射到主机上，但实际上 cloudreve 压根不会读取这个目录下的东西所以做了个小修改
2. Integrate aria2c support
There's no vanilla support for aria2c in the docker image so I made one. It would generate aria2c password and print it in the log during first startup so that user can paste the password in the control panel and it now works.
在 Docker 镜像里集成了 …
=> Integrate aria2c support & fix unintended behavior for docker image

models/folder.go, models/folder_test.go
when the id of destination folder inside the id set of moved folder, will cause an error that the parent of this folder will be itself, not an really error since the frontend forbidden this move action, but still an issue in some specific scenarios.
=> Fix: trigger err when move folder into itself

pkg/filesystem/driver/qiniu/handler.go, pkg/filesystem/driver/upyun/handler.go
本 PR 修正了七牛云、又拍云 Get 方法的问题，该问题会导致调用方法时发生 `nil pointer dereference`。
该问题会导致包括多文件压缩在内的若干功能无法正常使用。
=> fix: 七牛云与又拍云存储读取时发生 nil pointer dereference

pkg/webdav/prop.go
webdav响应中content-type全部为空，通过文件扩展名进行判断
=> webdav通过文件扩展名判断content-type

main.go, pkg/conf/conf.go, pkg/conf/defaults.go
cloudreve监听unix时日志中客户端ip为空，添加选择项从哪个header获取，默认为"X-Forwarded-For"
=> 修复unix下日志客户端ip为空，添加配置项设置从哪个header获取

service/admin/site.go
Summary in admin dashboard caching was introduced in [0c9383](https://github.com/cloudreve/Cloudreve/commit/0c9383e329542c5dad94f7560190cde04e93f6af).
It calls `cache.Set` function but doesn't handle errors.
If the user enables Redis, it won't successfully set cache because the type of the value cannot be serialized using gob, which is `map[string]interface{}`
So, we registered the types and fixed that.
=> Fix: admin summary cannot be cached in redis

Dockerfile, build.sh
Create-React-App uses the `GENERATE_SOURCEMAP` variable to control whether to generate map files, the default is `true`.
We can set it to `false` to avoid the generation of map files and the presence of map files in js files, which can avoid many warning events generated by the browser console because the map file cannot be found.
=> Better way to remove frontend map files

models/file.go, models/file_test.go
Fix deleting an empty folder takes a too long time when the size of files is large.
Empty folders have no children, so the parameter of `RemoveFilesWithSoftLinks` is also an empty slice. Then, it builds and executes a query `SELECT * FROM files` with no `WHERE` conditions, which takes the longest time.
=> Fix: unexpected querying all files when deleting an empty folder

pkg/filesystem/driver/s3/handler.go
=> Fix: s3(minio) file remove operation hang

Dockerfile
webpack v4 使用的 OpenSSL 组件库与高级版本的 NodeJS 使用的新版不兼容，导致使用 Node v16+ 版本构建时会报出  `error:0308010C:digital envelope routines::unsupported` 错误。其中一种解决方案自然是将 NodeJS 版本限定在 16 及以下，但更为推荐的解决方案是暂时使用 `NODE_OPTIONS=--openssl-legacy-provider` 规避，并尝试升级 webpack 相关的组件。
（不过尝试直接升级 webpack 会构建失败，估计是一些依赖版本的问题，没有多尝试，暂时先用旧版支持库应应急吧
=> fix: docker build failed

Dockerfile, build.sh
most time when a change modified the `build.sh` file, it has to change the `Dockerfile` as well, just for keeping one same build step, this is not easy to check if these to files got a gap
- the image size should as same as the originanl one
- we can see from the dive info below that there still a lot of space for reduce the image size, maybe this will be fixed later since this is just not an optimization change
=> Build docker image with build.sh file

pkg/filesystem/driver/s3/handler.go
建议更换成更好的 HeadObject 方法因为 HeadObject 方法并不会返回文件 Body 因此不需要 defer res.Body.Close()
=> 建议 Meta 获取文件信息

service/admin/policy.go
Execute a single SQL instead of a batch of slow searches.
=> Enhance(dashboard): optimize get policies request

models/init.go, pkg/conf/conf.go, pkg/conf/defaults.go
=> feat(db): support connect to mysql with unix socket

go.mod, go.sum, models/dialect_sqlite.go, models/folder_test.go, models/init.go, models/migration_test.go, pkg/util/common_test.go
sqlite 驱动从 github.com/jinzhu/gorm/dialects/sqlite 改为 github.com/glebarez/go-sqlite，以移除对 cgo 的依赖
TODO: 之前的  github.com/jinzhu/gorm 项目已经移至  github.com/go-gorm/gorm，并支持更多的特性
=> sqlite 驱动从 github.com/jinzhu/gorm/dialects/sqlite 改为 github.com/glebarez/go-sqlite

Dockerfile, README.md, README_zh-CN.md, Taskfile.yaml
add go-task support
Signed-off-by: kovacs <mritd@linux.com>
=> chore(build): add go-task support

pkg/webdav/file.go
我正在使用 [Swift backup](https://play.google.com/store/apps/details?id=org.swiftapps.swiftbackup&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1) 备份手机数据，该软件具有 webdav 支持。
但我在更新备份时，会报告 Server 500 错误，问题发生在 webdav 的 moveFiles 操作。
根据我的分析，确认是 overwrite  未实现带来的文件名冲突问题。
此 PR 目的为修复这个错误。
=> feat(Webdav): Add overwrite support for moveFiles and copyFiles

models/policy.go, models/policy_test.go
后端增加原始文件名无后缀魔法变量，前端：https://github.com/cloudreve/frontend/pull/155
=> 增加原始文件名无后缀魔法变量

go.mod, go.sum, pkg/cache/driver.go, pkg/cache/redis.go, pkg/cache/redis_test.go, pkg/conf/conf.go
替换Golang Redis依赖: redigo的版本至当前最新版1.8.9
（v2.0.0被标记为已撤回，且长期未更新）
Redis 6 及以上版本均可把ACL配置为使用username+password认证的状态，
虽然考虑到实际情况大概率也没人折腾redis的ACL就是了（
=> 为Redis数据库的连接信息添加Username字段

service/explorer/file.go
Fix: doc preview src of local storage policy starts with ":/" (#1842)
=> Fix: doc preview src of local storage policy starts with ":/" (#1842)

pkg/email/smtp.go
Add Message-ID to the mail service header to adapt to services such as Gmail
=> Fix: Adapt to Gmail.

inventory/setting.go, pkg/setting/provider.go, pkg/setting/types.go, service/basic/site.go
https://github.com/cloudreve/cloudreve/issues/2584
- Added "Asset Server Source" option for Cap Captcha (jsDelivr, unpkg, or self-hosted).
- Updated admin UI and translations.
- Frontend loads assets based on selected source.
=> feat(captcha): update static asset source option

inventory/client.go, pkg/conf/types.go
修复了 4.1.0 版本中MariaDB未能被识别的 bug，本次测试构建后可以正常运行
=> fix(db): 将MariaDB数据库类型映射到MySQL类型

inventory/group.go
This is another solution for #2592, [cloudreve/frontend#271](https://github.com/cloudreve/frontend/pull/271)
Unified for logical judgment conditions in create group and update group
=> [paln B] fix: new user group error in without replication
